import type { Task } from "types/index";

export const tasksMock: Task[]= [
  {
    createdBy: 'Ola Nordmann',
    createdDate: new Date(),
    error: '',
    lock: false,
    logicId: '1234',
    logicName: 'new-logic',
    runtimeSequenceId: '1',
    triggerItems: null,
    updatedBy: 'Kari Nordmann',
    updatedDate: new Date(),
    version: '',
    targetAssignment:{_id:'',name:'',interfaceOption:'ui-1'},
    _id: '',
    end_time: null,
    start_time: null,
    context: null,
  },
  {
    createdBy: 'Ola Nordmann',
    createdDate: new Date(),
    error: '',
    lock: false,
    logicId: '1234',
    logicName: 'new-logic',
    runtimeSequenceId: '2',
    triggerItems: null,
    updatedBy: 'Ola Nordmann',
    updatedDate: new Date(),
    version: '',
    targetAssignment:{_id:'',name:'',interfaceOption:'ui-2'},
    _id: '',
    end_time: null,
    start_time: null,
    context: null,
  },
];