/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksUi1IdIndexRouteImport } from './routes/tasks/ui1/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksUi1IdIndexRoute = TasksUi1IdIndexRouteImport.update({
  id: '/tasks/ui1/$id/',
  path: '/tasks/ui1/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tasks/ui1/$id': typeof TasksUi1IdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tasks/ui1/$id': typeof TasksUi1IdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tasks/ui1/$id/': typeof TasksUi1IdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tasks/ui1/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tasks/ui1/$id'
  id: '__root__' | '/' | '/tasks/ui1/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TasksUi1IdIndexRoute: typeof TasksUi1IdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/ui1/$id/': {
      id: '/tasks/ui1/$id/'
      path: '/tasks/ui1/$id'
      fullPath: '/tasks/ui1/$id'
      preLoaderRoute: typeof TasksUi1IdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TasksUi1IdIndexRoute: TasksUi1IdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
