/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './logics/__root'
import { Route as SampleLogicRouteRouteImport } from './logics/sample-logic/route'
import { Route as IndexRouteImport } from './logics/index'
import { Route as SampleLogicUi1IdIndexRouteImport } from './logics/sample-logic/ui-1/$id/index'

const SampleLogicRouteRoute = SampleLogicRouteRouteImport.update({
  id: '/sample-logic',
  path: '/sample-logic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleLogicUi1IdIndexRoute = SampleLogicUi1IdIndexRouteImport.update({
  id: '/ui-1/$id/',
  path: '/ui-1/$id/',
  getParentRoute: () => SampleLogicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sample-logic': typeof SampleLogicRouteRouteWithChildren
  '/sample-logic/ui-1/$id': typeof SampleLogicUi1IdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sample-logic': typeof SampleLogicRouteRouteWithChildren
  '/sample-logic/ui-1/$id': typeof SampleLogicUi1IdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sample-logic': typeof SampleLogicRouteRouteWithChildren
  '/sample-logic/ui-1/$id/': typeof SampleLogicUi1IdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sample-logic' | '/sample-logic/ui-1/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sample-logic' | '/sample-logic/ui-1/$id'
  id: '__root__' | '/' | '/sample-logic' | '/sample-logic/ui-1/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SampleLogicRouteRoute: typeof SampleLogicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sample-logic': {
      id: '/sample-logic'
      path: '/sample-logic'
      fullPath: '/sample-logic'
      preLoaderRoute: typeof SampleLogicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-logic/ui-1/$id/': {
      id: '/sample-logic/ui-1/$id/'
      path: '/ui-1/$id'
      fullPath: '/sample-logic/ui-1/$id'
      preLoaderRoute: typeof SampleLogicUi1IdIndexRouteImport
      parentRoute: typeof SampleLogicRouteRoute
    }
  }
}

interface SampleLogicRouteRouteChildren {
  SampleLogicUi1IdIndexRoute: typeof SampleLogicUi1IdIndexRoute
}

const SampleLogicRouteRouteChildren: SampleLogicRouteRouteChildren = {
  SampleLogicUi1IdIndexRoute: SampleLogicUi1IdIndexRoute,
}

const SampleLogicRouteRouteWithChildren =
  SampleLogicRouteRoute._addFileChildren(SampleLogicRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SampleLogicRouteRoute: SampleLogicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
